### ISSUE TITLE
How to use `group` or `keyBy` on the stream?

### ISSUE THREAD

**Issue by stairclimber** [reugn/go-streams#120]
After I read the example coud files in this repo. I cannot find a right way to achieve stream's `group` function or `keyBy` function. 
such as 'partition(stream, key=lambda x: x['country'])' in python streamz or `keyBy` in flink.

Usage Scene: Count the number of times each country appears in 100 pieces of data.

Maybe I was careless and didn't see the corresponding example. But anyway, I need your help and expect your reply

**Comment by reugn** [comment]
You're right, stream partitioning is not implemented yet. There are several utility methods available [here](https://github.com/reugn/go-streams/blob/v0.10.0/flow/util.go), but they may not be suitable for your specific requirements.

**Comment by stairclimber** [comment]
> You're right, stream partitioning is not implemented yet. There are several utility methods available [here](https://github.com/reugn/go-streams/blob/v0.10.0/flow/util.go), but they may not be suitable for your specific requirements.

Thanks for your quick reply, your reply saved me a lot of time. I wish your open source career will get better and better
