### ISSUE TITLE
Cannot import the `kafka` module

### ISSUE THREAD

**Issue by itaranto** [reugn/go-streams#126]
It seems the latest tag `'kafka@v0.1.2` is pointing to an incompatible version:

```sh
$ go get github.com/reugn/go-streams/kafka
go: github.com/reugn/go-streams/kafka imports
	github.com/reugn/go-streams/util: cannot find module providing package github.com/reugn/go-streams/util
```

**Comment by reugn** [comment]
The connector modules have not been released recently. You will need to retrieve a compatible version using [version queries](https://go.dev/ref/mod#version-queries).

**Comment by itaranto** [comment]
> The connector modules have not been released recently. You will need to retrieve a compatible version using [version queries](https://go.dev/ref/mod#version-queries).

Yes, that's what I thought.

 I used the commit hash for this.
