### ISSUE TITLE
the problem with fanout function 

### ISSUE THREAD

**Issue by sadnessly** [reugn/go-streams#22]
I test the fanout function in flow_test.go, it seems not correct when I add another flow.
`var toReture = func(in interface{}) interface{} {
	msg := in.(string)
	return msg
}`

`func TestFlowUtil(t *testing.T) {
	in := make(chan interface{})
	out := make(chan interface{})
	source := ext.NewChanSource(in)
	flow1 := flow.NewMap(toUpper, 1)
	flow2 := flow.NewMap(toReture, 1)
	filter := flow.NewFilter(filterA, 1)
	sink := ext.NewChanSink(out)
	var _input = []string{"a", "b", "c"}
	var _expectedOutput = []string{"b", "b", "c", "c"}
	go ingest(_input, in)
	go deferClose(in, time.Second*10)
	go func() {
		fanOut := flow.FanOut(source.Via(filter).Via(flow1).Via(flow2, 2)
		fanOut[1].To(sink)
	}()
	var _output []string
	for e := range sink.Out {
		_output = append(_output, e.(string))
	}
	sort.Strings(_output)
	assertEqual(t, _expectedOutput, _output)
}`
The function 'toReture' does nothing ,but it return incorrect result.

**Comment by reugn** [comment]
@sadnessly Thanks for pointing this out. Opened a pull request that fixes it.
Feel free to reopen or submit another issue if you spot any problem.
