### ISSUE TITLE
kafka shutdown, repeat consumption

### ISSUE THREAD

**Issue by Doslin** [reugn/go-streams#32]

**Comment by reugn** [comment]
@Doslin the Kafka connector should resume consumption when the cluster is up again. Could you please post here your logs.

**Comment by Doslin** [comment]
Sorry i described it wrong。
Will lose data when restart program ?

**Comment by reugn** [comment]
@Doslin , if you restart your application, there could be a message re-consumption since Kafka connector marks offset for each consumed message for further asynchronous commit. In some scenarios, data loss can take place, as well.

**Comment by Doslin** [comment]
ok , I still have a question
how to batch insert kafka

**Comment by reugn** [comment]
There is no bulk insertion API available. You can tune commits using the Sarama Flush configuration.
https://github.com/Shopify/sarama/blob/master/config.go#L203

**Comment by Doslin** [comment]
OK  ,thank you
