### ISSUE TITLE
Support for loop/feedback in the graph

### ISSUE THREAD

**Issue by dumblob** [reugn/go-streams#47]
I wonder whether this library supports loop/feedback constructs. Skimming the API gave a hint it shall be possible but I wonder about real world implications.

Any insights? Thanks!

**Comment by reugn** [comment]
If I understand correctly, you can achieve this if the source and destination both read/write from/to the same location.

**Comment by dumblob** [comment]
Ok, if there are no known issues or quirks, then that is great news. I might give it a shot for this purpose!
