### ISSUE TITLE
Kafka messages should be processed in parallel

### ISSUE THREAD

**Issue by dellekappa** [reugn/go-streams#52]
Hi,

I was looking at [row 133 of kafka_sarama.go](https://github.com/reugn/go-streams/blob/b642dd83af2e9def0f5535a0173f7df07bd02ac2/kafka/kafka_sarama.go#L133) source code and noticed that every consumed message are pushed to the same channel.
If I'm correct, this have the effect to make the processing of the messages to be sequential, loosing the possibility of processing the partitions in parallel.
Could it make sense to have a channel per partition in this case?

**Comment by reugn** [comment]
@dellekappa, a `streams.Source` can only return one channel in its `Out()` implementation, which makes parallel consumption inapplicable. Feel free to reopen if you have more questions.
