### ISSUE TITLE
Are there plans to support generics?

### ISSUE THREAD

**Issue by dalianzhu** [reugn/go-streams#58]
If no one else is interested, I want to do.
This neat framework is awesome. :)

**Comment by reugn** [comment]
Thank you @dalianzhu. The Flows already use generic functions, see: 
https://github.com/reugn/go-streams/blob/master/flow/filter.go#L8 
https://github.com/reugn/go-streams/blob/master/flow/map.go#L8 
If you have suggestions for improvement, let's discuss.

**Comment by dalianzhu** [comment]
awesome, the latest version already supports generics
https://github.com/reugn/go-streams/blob/40a238463badbd07e49fef20f80f6fd579bc5172/flow/filter.go#L78-L83

found a small problem, if the filter function type do not match, will raise a runtime error.

I try to find a way **to check types during compilation**, but this also has a lot of problems

i tried an idea:
```
type Filter[T, FlowR any] struct {
	filterPredicate FilterPredicate[T]
	in              chan T
	out             chan T
	parallelism     uint
}

// Via streams data through the given flow
func (f *Filter[T, FlowR]) Via(flow streams.Flow[T, FlowR]) streams.Flow[T, FlowR] {
	go f.transmit(flow)
	return flow
}
```

but the type of FlowR must be determined when the filter is created, is not good, it makes the following usage fail
```
// ft: *Filter[int,string]
ft.Via(flow.NewMap(func(i int) string {return ""}) // ok
ft.Via(flow.NewMap(func(i int) int{return ""}) // error
```

go doesn't seem to support method generics, if I can write code like this, it would work fine:
```
// error code, method not support generics
func (f *Filter[T]) Via[FlowR any](flow streams.Flow[T, FlowR]) streams.Flow[T, FlowR] { 
	go f.transmit(flow)
	return flow
}
```

I have to think again

**Comment by pckhoi** [comment]
Any plan to change `Inlet` and `Outlet` to generic interfaces? Consequently, I guess `Sink`, `Source`, and `Flow` will all become generics. I think it offers more type safety.
