### ISSUE TITLE
Example code for Kafka - failed with panic 

### ISSUE THREAD

**Issue by tzichtig** [reugn/go-streams#63]
go version -1.19.5
kafka version -2.8.1

When I try to run the example for kafka I get panic error

panic: interface conversion: interface {} is []interface {}, not []*sarama.ConsumerMessage   goroutine 13 [running]: github.com/reugn/go-streams/flow.(*FlatMap[...]).doStream(0xc000028a60) ####/go/pkg/mod/github.com/reugn/go-streams@v0.8.0/flow/flat_map.go:81 +0x310 created by github.com/reugn/go-streams/flow.NewFlatMap[...] ####go/pkg/mod/github.com/reugn/go-streams@v0.8.0/flow/flat_map.go:38 +0x17c

this come from  this function 

```
var appendAsterisk = func(inArr []*sarama.ConsumerMessage) []*sarama.ConsumerMessage {
	outArr := make([]*sarama.ConsumerMessage, len(inArr))
	for i, msg := range inArr {
		msg.Value = []byte(string(msg.Value) + "*")
		outArr[i] = msg
	}
	return outArr
}

```
when i change code to : 

```
var appendAsterisk = func(inArr []interface{}) []*sarama.ConsumerMessage {
	outArr := make([]*sarama.ConsumerMessage, len(inArr))
	for i, msg := range inArr {

		if value, ok := msg.(*sarama.ConsumerMessage); ok {
			//you can use variable `value`
			value.Value = []byte(string(value.Value) + "*")
			outArr[i] = value
		}
	}
	return outArr
}

```
its fine

**Comment by reugn** [comment]
PR #104 introduces a breaking change by making the `TumblingWindow` flow generic. This resolves the panic issue on interface conversion in the Kafka example.
