### ISSUE TITLE
Nats de-duplication matches Kafka 

### ISSUE THREAD

**Issue by gedw99** [reugn/go-streams#70]
https://nats.io/blog/new-per-subject-discard-policy/

Probably worth turning this on as a default in go-streams ? 

It removes sone hairy race conditions

**Comment by reugn** [comment]
@gedw99, PR #109 refactors the JetStream connectors, and makes the stream a prerequisite. The examples section creates a stream using the `DiscardNewPerSubject` property and mentions the stream configuration page for additional options available.

**Comment by gedw99** [comment]
Thanks @reugn
