### ISSUE TITLE
how to handle the message and ignore the sink process

### ISSUE THREAD

**Issue by jeven2016** [reugn/go-streams#81]
Hi developer,
    normally the code should be written like this :   source().Map().To(sink). But how to handle the messages if no need to provide sink that means no further consumer cares about it anymore. and the code could be like this:   source().Map().End().

Thanks for your great lib ~~~

**Comment by reugn** [comment]
Hi @jeven2016, you can use the following pattern
```go
source.
    Via(mapFunc).
    To(extension.NewIgnoreSink())
```

**Comment by jeven2016** [comment]
> 

Thanks, : ) , it works~~~
