### ISSUE TITLE
 It would be great if there was a document or tutorial

### ISSUE THREAD

**Issue by ghost** [reugn/go-streams#88]
go-streams is a very succinct library and it is suitable for my usage scenario. 
but, I had a lot of question during use it. such as:
1. Can I change variables outside? how to?
2. Can I define my own source receiver?
3. etc....
I believe that the lack of documentation dissuades many people who want to use go-streams.
The documentation does not have to be as detailed as flink, but it can clearly mark common usage and points that need attention.

**Comment by reugn** [comment]
Hi, @b1tkeeper. There is no documentation page other than [pkg.go.dev](https://pkg.go.dev/github.com/reugn/go-streams) that outlines the main things. While this is quite descriptive, I understand that there will be additional questions clarifying various use cases. To your points:
1. In the transformer Flows (like Map), side effects can be implemented using regular closures, and the user will have to take care of synchronization.
2. The users can implement their own connectors and flows by implementing the [stream interfaces](https://github.com/reugn/go-streams/blob/master/streams.go). An existing implementation can be taken as a reference.
3. I agree. I will consider creating an FAQ section for the most common questions.
